version: 2

sources:
    - name: staging
      #For bigquery:
      database: tully-test
      schema: trips_data_all

      tables:
        - name: nytaxi
         # freshness:
           # error_after: {count: 6, period: hour}